# coding: utf-8
# strings.py - Translations for the Kochbuch project

TRANSLATIONS = {
    'de': {
        'title': 'Rezepte',
        'title_admin':'Verwaltung',
        'title_extended_search': 'Erweiterte Suche',
        'welcome': 'Willkommen in der Hexenküche',
        'search_placeholder': 'Suche nach Rezepten...',
        'btn_new': '[ NEUES REZEPT ERSTELLEN ]',
        'btn_kochbuch': '[ KOCHBUCH ]',
        'no_recipes': 'Keine Rezepte gefunden.',
		'cancel':'Abbrechen',
        'save': 'Speichern',
		'edit_button_text': 'Rezept bearbeiten',
		'edit_button': 'Bearbeiten',
		'delete_button': 'Löschen',
		'edit_button': 'Bearbeiten',
		'delete_confirm': 'Dieses Rezept wirklich löschen?',
		'back_to_db': 'Zurück zur Übersicht',
		'search_title': 'Titel:',
		'search_category': 'Kategorie:',
		'search_ingredients': 'Zutaten:',
		'search_button': 'Suchen',
		'create_recipe': 'Neues Rezept',
		'import_recipe': 'Rezept importieren',
		'choose_file': 'Datei auswählen',
		'import_success': 'Rezepte erfolgreich importiert!',
		'search_success': 'Rezepte gefunden',
		'choose_file': 'XML-Datei auswählen',
		'import_button': 'Importieren',
		'upload_text': 'Wähle eine XML-Datei aus, um Rezepte in die Datenbank zu laden',
		'browse': 'Ja wo isse denn?',
		"title_label": "Titel",
		"synopsis": "Anmerkungen",
        "servings_label": "Portionen",
        "tested_label": "schon ausprobiert",
        "cat_label": "Kategorien",
        "source_label": "Quelle",
        "image_label": "Bilddatei (Name)",
        "ingredients_title": "Zutaten",
        "instructions_title": "Anleitung",
        "notes_title": "Anmerkungen",
        "save_btn": "Rezept speichern",
        "yes": "Ja",
        "no": "Nein",
        "amount_head": "Menge",
        "unit_head": "Einheit",
        "ing_head": "Zutat",
        "ing_or_title":"Zutat oder Zwischentitel:",
        "add_ingredient": "Zutat hinzufügen"
        },
    'en': {
        'title': 'Recipes Database',
        'title_admin':'Maintenance',
        'title_extended_search': 'Extended Search',
        'welcome': 'Welcome to the Secret Lab',
        'search_placeholder': 'Search for recipes...',
        'btn_new': '[ CREATE NEW RECIPE ]',
        'btn_kochbuch': '[ COOKBOOK ]',
        'no_recipes': 'No recipes found.',
        'cancel':'Cancel',
		'save': 'Save',
		'edit_button_text': 'Edit Recipe',
		'edit_button': 'Edit',
		'delete_button': 'Delete',
		'delete_confirm': 'Really delete this recipe?',
		'back_to_db': 'Back to Database',
		'search_title': 'Title:',
		'search_category': 'Category:',
		'search_ingredients': 'Ingredients:',
		'search_button': 'Search',
		'create_recipe': 'Create New Recipe',
		'import_recipe': 'Import Recipe',
		'choose_file':'Choose Upload File',
		'import_success': 'Recipes imported!',
		'search_success': 'Recipes found',
		'choose_file': 'Select XML file',
		'import_button': 'Import',
		'upload_text': 'Select a file for Upload',
		'browse': 'Browse',
		"title_label": "Title",
		"synopsis": "Synopsis",
        "servings_label": "Servings",
        "tested_label": "Already cooked",
        "cat_label": "Categories",
        "source_label": "Source",
        "image_label": "Image File (name)",
        "ingredients_title": "Ingredients",
        "instructions_title": "Instructions",
        "notes_title": "Notes",
        "save_btn": "Save Recipe",
        "yes": "Yes",
        "no": "No",
        "amount_head": "Qty",
        "unit_head": "Unit",
        "ing_head": "Ingredient",
        "ing_or_title":"Ingredient or Subtitle:",
		"add_ingredient": "Add Ingredient"
    }
}
