# coding: utf-8
# strings.py - Translations for the Kochbuch project

TRANSLATIONS = {
    'de': {
        'title': 'Rezepte',
        'welcome': 'Willkommen in der Hexenküche',
        'search_placeholder': 'Suche nach Rezepten...',
        'btn_new': '[ NEUES REZEPT ERSTELLEN ]',
        'btn_kochbuch': '[ KOCHBUCH ]',
        'no_recipes': 'Keine Rezepte gefunden.',
    'cancel':'Abbrechen',
        'save': 'Speichern',
    'edit_button_text': 'Rezept bearbeiten',
    'delete_button': 'Löschen',
    'delete_confirm': 'Dieses Rezept wirklich löschen?',
    'back_to_db': 'Zurück zur Übersicht',
    'search':'Suchen...',
'search_title': 'Titel:',
'search_category': 'Kategorie:',
'search_ingredients': 'Zutaten:',
'search_button': 'Suchen',
'create_recipe': 'Neues Rezept',
'import_recipe': 'Rezept importieren',
'choose_file': 'Datei auswählen',
'import_success': 'Rezepte erfolgreich importiert!',
'choose_file': 'XML-Datei auswählen',
'import_button': 'Importieren',
'upload_text': 'Wähle eine XML-Datei aus, um Rezepte in die Datenbank zu laden',
'browse': 'Ja wo isse denn?'
},
    'en': {
        'title': 'Recipes Database',
        'welcome': 'Welcome to the Secret Lab',
        'search_placeholder': 'Search for recipes...',
        'btn_new': '[ CREATE NEW RECIPE ]',
        'btn_kochbuch': '[ COOKBOOK ]',
        'no_recipes': 'No recipes found.',
        'cancel':'Cancel',
    'save': 'Save',
    'edit_button_text': 'Edit Recipe',
    'delete_button': 'Delete',
    'delete_confirm': 'Really delete this recipe?',
    'back_to_db': 'Back to Database',
    'search':'Search...',
'search_title': 'Title:',
'search_category': 'Category:',
'search_ingredients': 'Ingredients:',
'search_button': 'Search',
'create_recipe': 'Create New Recipe',
'import_recipe': 'Import Recipe',
'choose_file':'Choose Upload File',
'import_success': 'Recipes imported!',
'choose_file': 'Select XML file',
'import_button': 'Import',
'upload_text': 'Select a file for Upload',
'browse': "Browse"
    }
}
